name: Build and Package Electron Shiny App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   node-version: '20'
          #   arch: x64
          #   build-script: build:mac-x64
          #   artifact-name: BIGApp-mac-x64
          - os: macos-latest
            node-version: '20'
            arch: arm64
            build-script: build:mac-arm64
            artifact-name: EA-mac-arm64
          - os: windows-latest
            node-version: '20'
            arch: x64
            build-script: build:win
            artifact-name: EA-windows
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('electron_app/package-lock.json') }}

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci
        working-directory: electron_app

      # Set up R 4.2.2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      # - name: Install gfortran from CRAN (Intel macOS)
      #   if: runner.os == 'macOS' && matrix.arch == 'x64'
      #   run: |
      #     curl -LO https://mac.r-project.org/tools/gfortran-12.2-universal.pkg 
      #     sudo installer -pkg gfortran-12.2-universal.pkg  -target /
          
      #     which gfortran
      #     gfortran --version

      # Install gfortran from CRAN on macOS (Apple Silicon)
      - name: Install gfortran from CRAN (Apple Silicon)
        if: runner.os == 'macOS' && matrix.arch == 'arm64'
        run: |
          curl -LO https://mac.r-project.org/tools/gfortran-12.2-universal.pkg 
          
          sudo installer -pkg gfortran-12.2-universal.pkg  -target /
          
          which gfortran
          gfortran --version

      # Install R packages
      - name: Install R packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          RENV_CONFIG_AUTO_ACTIVATE: FALSE
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cran.rstudio.com")'
          # Rscript -e 'remotes::install_github("jendelman/GWASpoly")'
          # Rscript -e 'remotes::install_github("Breeding-Insight/BIGr")'
          # Rscript -e 'install.packages(c("golem", "httpuv", "shiny", "vcfR", "adegenet", "DT", "dplyr", "bs4Dash", "ggplot2", "purrr", "scales", "shinyWidgets", "shinydisconnect", "shinyalert", "shinyjs", "stringr", "tidyr", "updog", "AGHmatrix", "factoextra", "future", "shinycssloaders", "RColorBrewer", "tibble", "plotly", "rrBLUP", "MASS", "config", "Matrix", "matrixcalc", "markdown"), repos = "https://cran.rstudio.com")'

      #  # Verify R Installation on Windows (Optional)
      # - name: Verify R Installation (Windows)
      #   if: runner.os == 'Windows'
      #   shell: pwsh
      #   run: |
      #     # Check R version
      #     Rscript --vanilla -e "R.version.string"
  
      #     # Verify R_HOME
      #     $R_HOME = Rscript --vanilla -e "cat(R.home())"
      #     Write-Output "R_HOME is $R_HOME"
  
      #     # List R_HOME contents
      #     Get-ChildItem -Path $R_HOME | Sort-Object Name | Select-Object Name

      # Copy R into app directory (for macOS)
      - name: Copy R into app directory (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p electron_app/R
          cp -R "$(Rscript --vanilla -e "cat(R.home())")/." electron_app/R/

      # Copy R into app directory (for Windows)
      - name: Copy R into app directory (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Create the target directory
          mkdir -Path electron_app\R -Force
  
          # Retrieve R_HOME using Rscript with --vanilla to prevent renv activation
          $R_HOME = Rscript --vanilla -e "cat(R.home())"
  
          # Output R_HOME for debugging
          Write-Output "R_HOME is $R_HOME"
  
          # Check if R_HOME directory exists
          if (Test-Path $R_HOME) {
            Write-Output "R_HOME directory exists."
          } else {
            Write-Error "R_HOME directory does not exist at $R_HOME"
            exit 1
          }
  
          # List contents of R_HOME for verification
          Get-ChildItem -Path $R_HOME -Recurse | Sort-Object FullName | Select-Object FullName
  
          # Copy R files to the app directory
          xcopy "$R_HOME\*" "electron_app\R\" /E /I /Y

      - name: List R directory contents
        run: |
          ls -R electron_app/R

      # Build the Electron app
      - name: Build Electron App
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run ${{ matrix.build-script }}
        working-directory: electron_app

      # Upload the built application
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: electron_app/dist/*